name: Production
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install all dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${secrets.SSH_USERNAME}




      # - 
      # - run: yarn install --frozen-lockfile
      # - run: yarn build