name: Production Deployment
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build & Deploy for Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
      - name: executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: | 
            sudo ln -s "$NVM_DIR/versions/node/0.39.1/bin/node" "/usr/local/bin/node"
            sudo ln -s "$NVM_DIR/versions/node/0.39.1/bin/npm" "/usr/local/bin/npm"
            sudo ln -s "$NVM_DIR/versions/node/0.39.1/bin/pm2" "/usr/local/bin/pm2"
            pm2 restart ${{ secrets.APP_NAME }}
 
